# Generated by Django 5.2.4 on 2026-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_studentattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
