# Generated by Django 5.2.4 on 2026-01-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_studentattendance_deleted_at_and_more'),
        ('school_admin', '0016_auditlog_school_admi_timesta_6167c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='attendances_date_2aaae1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['is_deleted'], name='attendances_is_dele_ae62e0_idx'),
        ),
    ]
