# Generated by Django 5.2.4 on 2026-01-26 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0016_auditlog_school_admi_timesta_6167c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('book', 'E-Book / PDF'), ('video', 'Video Lesson'), ('document', 'Study Material / Doc'), ('link', 'External Reference')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_locker/files/')),
                ('external_url', models.URLField(blank=True, help_text='Link to YouTube, Google Drive, etc.', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='learning_locker/thumbs/')),
                ('is_platform_global', models.BooleanField(default=False, help_text='If checked, this item is provided by Super Admin and visible to all students.')),
                ('school_wide', models.BooleanField(default=False, help_text='If checked, every student in this school can see this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_classrooms', models.ManyToManyField(blank=True, related_name='resources', to='school_admin.classroom')),
                ('target_levels', models.ManyToManyField(blank=True, related_name='resources', to='school_admin.gradelevel')),
                ('target_subjects', models.ManyToManyField(blank=True, related_name='resources', to='school_admin.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
