# Generated by Django 5.2.4 on 2025-12-24 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('super_admin', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.subscriptionplan'),
        ),
    ]
