# Generated by Django 5.2.4 on 2026-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
