# Generated by Django 5.2.4 on 2025-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='EduManage High School', max_length=255)),
                ('address', models.TextField(default='123 Education Lane, Knowledge City')),
                ('email', models.EmailField(default='contact@edumanage.com', max_length=254)),
                ('phone', models.CharField(default='+1 234 567 890', max_length=50)),
                ('enable_whiteboard', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
            ],
        ),
    ]
