# Generated by Django 5.2.4 on 2025-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#4a90e2', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(default='#2c3e50', max_length=20),
        ),
    ]
