# Generated by Django 5.2.4 on 2025-12-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_schoolsettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
