# Generated by Django 5.2.4 on 2025-12-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0006_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='grade_levels', to='school_admin.subject'),
        ),
    ]
