# Generated by Django 5.2.4 on 2025-12-29 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_gradelevel_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this promotion')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='school_admin.classroom')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='school_admin.gradelevel')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_performed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to=settings.AUTH_USER_MODEL)),
                ('to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='school_admin.classroom')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='school_admin.gradelevel')),
            ],
            options={
                'ordering': ['-promotion_date'],
            },
        ),
    ]
