# Generated by Django 5.2.4 on 2026-01-04 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_promotionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('event', 'General Event'), ('holiday', 'Holiday'), ('exam', 'Examination'), ('meeting', 'Meeting'), ('other', 'Other')], default='event', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Calendar Event',
                'verbose_name_plural': 'School Calendar Events',
                'ordering': ['start_date'],
            },
        ),
    ]
