# Generated by Django 5.2.4 on 2026-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0009_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_attendance',
            field=models.BooleanField(default=True),
        ),
    ]
