# Generated by Django 5.2.4 on 2026-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0010_schoolsettings_enable_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
