# Generated by Django 5.2.4 on 2026-01-12 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0011_schoolsettings_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, help_text='Form teacher responsible for this class', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_class', to=settings.AUTH_USER_MODEL),
        ),
    ]
