# Generated by Django 5.2.4 on 2026-01-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0012_classroom_homeroom_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., A, B+, C', max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Minimum percentage required for this grade', max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='GP value (e.g., 4.0)', max_digits=3)),
                ('color_code', models.CharField(default='#1e293b', help_text='Hex color for UI badges', max_length=20)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='cass_weight',
            field=models.PositiveIntegerField(default=40, help_text='Weight percentage for Continuous Assessment (0-100)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='exam_weight',
            field=models.PositiveIntegerField(default=60, help_text='Weight percentage for Exams (0-100)'),
        ),
    ]
