# Generated by Django 5.2.4 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0016_auditlog_school_admi_timesta_6167c2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('PROMOTION', 'Student Promotion'), ('SETTINGS', 'Settings Changed'), ('SECURITY', 'Security Event'), ('THROTTLE', 'IP Throttled')], max_length=20),
        ),
    ]
