"""
Django settings for school_portal project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-d)25&*9on(c$vc4vxln^354%849^_0elkav4-9^%3-x2*d+)^^'

# loads .env 
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Now read environment variables
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
# DEBUG = os.environ.get("DEBUG", "False") == "True"

DEBUG = True

AGORA_APP_ID = os.environ.get("AGORA_APP_ID", "").strip()
NETLESS_APP_ID = os.environ.get("NETLESS_APP_ID", "").strip() # Specific for Whiteboard
AGORA_REST_ID = os.environ.get("AGORA_REST_ID", "").strip()
AGORA_REST_CERTIFICATE = os.environ.get("AGORA_REST_CERTIFICATE", "").strip()
AGORA_APP_CERTIFICATE = os.environ.get("AGORA_APP_CERTIFICATE", "").strip()

# Fail fast if any critical key is missing (Using Agora for Whiteboard only now)
if not all([SECRET_KEY, AGORA_APP_ID, NETLESS_APP_ID, AGORA_REST_ID, AGORA_REST_CERTIFICATE]):
    raise RuntimeError("Missing critical environment variables in .env!")

if not AGORA_APP_CERTIFICATE:
    print("WARNING: AGORA_APP_CERTIFICATE is missing. Whiteboard video will not function.")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

SHARED_APPS = (
    'daphne',
    'channels', # Added channels
    'django_tenants', # Mandatory
    'myapps.customers', # Your Tenant/Domain models
    'myapps.accounts',  # ADDED: Allows Global Admins to live in Public Schema
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'rest_framework',
    'myapps.super_admin',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'myapps.accounts', 
    'myapps.core',
    'myapps.school_admin',
    'myapps.teacher',
    'myapps.student',
    'myapps.parent',
    'myapps.chat_system',
    'myapps.whiteboard',
    'myapps.attendances',
    'rest_framework',
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "customers.Client"
TENANT_DOMAIN_MODEL = "customers.Domain"

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'myapps.super_admin.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_portal.tenant_urls'
PUBLIC_SCHEMA_URLCONF = 'school_portal.public_urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapps.school_admin.context_processors.school_settings',
                'myapps.super_admin.context_processors.branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_portal.wsgi.application'
ASGI_APPLICATION = 'school_portal.asgi.application'

# CHANNEL_LAYERS: Production-grade Redis with Development-friendly In-Memory fallback
USE_REDIS = os.environ.get("USE_REDIS", "False") == "True"

if USE_REDIS:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(os.environ.get("REDIS_HOST", "127.0.0.1"), int(os.environ.get("REDIS_PORT", 6379)))],
            },
        },
    }
else:
    # Safe fallback for local development without Redis
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# DRF SETUP
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # ensures only logged-in users can access the API. Without this, your endpoints would be publicly accessible — huge security risk for a whiteboard app.
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # uses Django session (like when logged in via admin or frontend login form).
        'rest_framework.authentication.BasicAuthentication',  # simple HTTP Basic Auth (username/password).
        # Optional: JWT if you plan to use tokens
    ],
    # Optional: throttling for production
    'DEFAULT_THROTTLE_CLASSES': [ # Prevents spam/DoS attacks, which is critical for endpoints like get_room_token.
        'rest_framework.throttling.UserRateThrottle', # limits authenticated users.
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/day',   # each logged-in user can make 100 requests per day.
        'anon': '2/day',  # each anonymous user can make 2 requests per day.
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME', 'school_db'),
        'USER': os.environ.get('DB_USER', 'school_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'school_password'), # Only keep default for dev if really needed, better to rely on .env
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}
DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The custom user model
AUTH_USER_MODEL = 'accounts.User'

# Auth Redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/' # Redirect to home/dashboard after login
LOGOUT_REDIRECT_URL = '/login/'

# Agora Credentials


# set AGORA_APP_ID=ba25e5967aba4e959322196250dac65f
# set AGORA_REST_ID=uh90WmH02uo2GpbL
# set AGORA_REST_CERTIFICATE=W6NlmbFjSbPI7D2p8303XH_jrkrf7VNb


# TENANT_MODEL = "customers.Client"
# TENANT_DOMAIN_MODEL = "customers.Domain"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

MULTITENANT_RELATIVE_MEDIA_ROOT = "%s"
