# Generated by Django 5.2.4 on 2025-12-29 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0008_promotionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Current classroom section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='school_admin.classroom')),
                ('grade_level', models.ForeignKey(blank=True, help_text='Current grade level (e.g., Grade 10)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_admin.gradelevel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
