# Generated by Django 5.2.4 on 2025-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_promotionrecord'),
        ('whiteboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboardroom',
            name='allowed_classrooms',
            field=models.ManyToManyField(blank=True, related_name='whiteboard_rooms', to='school_admin.classroom'),
        ),
        migrations.AddField(
            model_name='whiteboardroom',
            name='allowed_grade_levels',
            field=models.ManyToManyField(blank=True, related_name='whiteboard_rooms', to='school_admin.gradelevel'),
        ),
    ]
