# Generated by Django 5.2.4 on 2025-12-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='system_logos/'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='platform_name',
            field=models.CharField(default='EduManage', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='primary_color',
            field=models.CharField(default='#4a90e2', max_length=7),
        ),
    ]
