# Generated by Django 5.2.4 on 2026-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_globalsetting_logo_globalsetting_platform_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('book', 'E-Book / PDF'), ('video', 'Video Lesson'), ('document', 'Study Material / Doc')], default='book', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='platform_resources/files/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Global Resource',
                'verbose_name_plural': 'Platform Global Resources',
            },
        ),
    ]
