# Generated by Django 5.2.4 on 2026-01-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_platformresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
