# Generated by Django 5.2.4 on 2026-01-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('cass', 'Continuous Assessment (CASS)'), ('exam', 'Examination')], default='cass', help_text='Categorize as CASS or Exam for weightage', max_length=10),
        ),
    ]
