# Generated by Django 5.2.4 on 2026-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_assignment_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_type',
        ),
        migrations.AddField(
            model_name='assignment',
            name='activity_type',
            field=models.CharField(choices=[('assignment', 'Assignment (Interactive)'), ('test', 'Test'), ('quiz', 'Quiz'), ('exam', 'Examination')], default='assignment', help_text='Specific type of activity', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('cass', 'Continuous Assessment (CASS)'), ('exam', 'Examination')], default='cass', help_text='Weightage Category', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_interactive',
            field=models.BooleanField(default=True, help_text='If True, students can submit files. If False, score-only.'),
        ),
    ]
