# Generated by Django 5.2.4 on 2026-01-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0014_academicyear_term'),
        ('teacher', '0004_remove_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='school_admin.term'),
        ),
    ]
