# Generated by Django 5.2.4 on 2026-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_grade_graded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
