# Generated by Django 5.2.4 on 2026-01-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_grade_deleted_at_grade_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['is_deleted'], name='teacher_gra_is_dele_7d3667_idx'),
        ),
    ]
